import {
  ServiceItem,
  TransactionRecord,
  VirtualNumberSession,
  EsimPackage,
  EsimSession,
  GiftCardRate,
  GiftCardTrade,
  SupportTicket,
  WalletBalance,
} from '@/types/jejelaye';

export const INITIAL_WALLET: WalletBalance = {
  balance: 68500.0,
  gift_card_balance: 142500.0,
  referral_balance: 4800.0,
  virtual_account: {
    bank_name: 'Wema Bank / Moniepoint',
    account_number: '7829104821',
    account_name: 'JejePay - Emmanuel Reseller',
  },
};

export const INITIAL_SERVICES: ServiceItem[] = [
  // AIRTIME
  { id: 101, name: 'MTN VTU Airtime', type: 'airtime', provider: 'MTN', price: 0, description: 'Instant top-up for all MTN lines' },
  { id: 102, name: 'Airtel Airtime', type: 'airtime', provider: 'Airtel', price: 0, description: 'Direct top-up for Airtel lines' },
  { id: 103, name: 'Glo VTU Airtime', type: 'airtime', provider: 'Glo', price: 0, description: 'Glo instant airtime recharge' },
  { id: 104, name: '9mobile Airtime', type: 'airtime', provider: '9mobile', price: 0, description: '9mobile instant VTU credit' },

  // DATA PLANS
  { id: 201, name: 'MTN SME Data 1GB', type: 'data', provider: 'MTN', price: 265, plan_id: 'mtn_sme_1gb', volume: '1GB', validity: '30 Days', description: 'Direct SME data bundle' },
  { id: 202, name: 'MTN SME Data 2GB', type: 'data', provider: 'MTN', price: 530, plan_id: 'mtn_sme_2gb', volume: '2GB', validity: '30 Days', description: 'Direct SME data bundle' },
  { id: 203, name: 'MTN SME Data 3GB', type: 'data', provider: 'MTN', price: 795, plan_id: 'mtn_sme_3gb', volume: '3GB', validity: '30 Days', description: 'Direct SME data bundle' },
  { id: 204, name: 'MTN SME Data 5GB', type: 'data', provider: 'MTN', price: 1325, plan_id: 'mtn_sme_5gb', volume: '5GB', validity: '30 Days', description: 'Direct SME data bundle' },
  { id: 205, name: 'MTN Corporate Gifting 10GB', type: 'data', provider: 'MTN', price: 2750, plan_id: 'mtn_corp_10gb', volume: '10GB', validity: '30 Days', description: 'Corporate fast delivery data' },

  { id: 206, name: 'Airtel CG Data 1GB', type: 'data', provider: 'Airtel', price: 290, plan_id: 'airtel_cg_1gb', volume: '1GB', validity: '30 Days', description: 'Airtel Corporate Gifting' },
  { id: 207, name: 'Airtel CG Data 2GB', type: 'data', provider: 'Airtel', price: 580, plan_id: 'airtel_cg_2gb', volume: '2GB', validity: '30 Days', description: 'Airtel Corporate Gifting' },
  { id: 208, name: 'Airtel CG Data 5GB', type: 'data', provider: 'Airtel', price: 1450, plan_id: 'airtel_cg_5gb', volume: '5GB', validity: '30 Days', description: 'Airtel Corporate Gifting' },
  { id: 209, name: 'Airtel CG Data 10GB', type: 'data', provider: 'Airtel', price: 2900, plan_id: 'airtel_cg_10gb', volume: '10GB', validity: '30 Days', description: 'Airtel Corporate Gifting' },

  { id: 210, name: 'Glo Corporate Data 1GB', type: 'data', provider: 'Glo', price: 250, plan_id: 'glo_corp_1gb', volume: '1GB', validity: '30 Days', description: 'Glo Corporate bundle' },
  { id: 211, name: 'Glo Corporate Data 2GB', type: 'data', provider: 'Glo', price: 500, plan_id: 'glo_corp_2gb', volume: '2GB', validity: '30 Days', description: 'Glo Corporate bundle' },
  { id: 212, name: 'Glo Corporate Data 5GB', type: 'data', provider: 'Glo', price: 1250, plan_id: 'glo_corp_5gb', volume: '5GB', validity: '30 Days', description: 'Glo Corporate bundle' },

  { id: 213, name: '9mobile SME Data 1.5GB', type: 'data', provider: '9mobile', price: 320, plan_id: '9mob_sme_1_5gb', volume: '1.5GB', validity: '30 Days', description: '9mobile SME data' },
  { id: 214, name: '9mobile SME Data 3GB', type: 'data', provider: '9mobile', price: 640, plan_id: '9mob_sme_3gb', volume: '3GB', validity: '30 Days', description: '9mobile SME data' },

  // ELECTRICITY
  { id: 301, name: 'Ikeja Electric (IKEDC)', type: 'electricity', provider: 'IKEDC', price: 0, description: 'Prepaid & Postpaid bill payment' },
  { id: 302, name: 'Eko Electric (EKEDC)', type: 'electricity', provider: 'EKEDC', price: 0, description: 'Prepaid & Postpaid bill payment' },
  { id: 303, name: 'Abuja Electric (AEDC)', type: 'electricity', provider: 'AEDC', price: 0, description: 'Prepaid & Postpaid bill payment' },
  { id: 304, name: 'Ibadan Electric (IBEDC)', type: 'electricity', provider: 'IBEDC', price: 0, description: 'Prepaid & Postpaid bill payment' },
  { id: 305, name: 'Enugu Electric (EEDC)', type: 'electricity', provider: 'EEDC', price: 0, description: 'Prepaid & Postpaid bill payment' },
  { id: 306, name: 'Port Harcourt (PHED)', type: 'electricity', provider: 'PHED', price: 0, description: 'Prepaid & Postpaid bill payment' },

  // TV SUBSCRIPTION
  { id: 401, name: 'DSTV Padi Bouquet', type: 'tv', provider: 'DSTV', price: 3600, plan_id: 'dstv_padi', description: '45+ channels' },
  { id: 402, name: 'DSTV Yanga Bouquet', type: 'tv', provider: 'DSTV', price: 5100, plan_id: 'dstv_yanga', description: '85+ channels' },
  { id: 403, name: 'DSTV Confam Bouquet', type: 'tv', provider: 'DSTV', price: 9300, plan_id: 'dstv_confam', description: '105+ channels' },
  { id: 404, name: 'DSTV Compact Bouquet', type: 'tv', provider: 'DSTV', price: 15700, plan_id: 'dstv_compact', description: '130+ channels Premier League' },
  { id: 405, name: 'GOtv Smallie Monthly', type: 'tv', provider: 'GOtv', price: 1575, plan_id: 'gotv_smallie', description: '35+ basic channels' },
  { id: 406, name: 'GOtv Jinja Bouquet', type: 'tv', provider: 'GOtv', price: 3300, plan_id: 'gotv_jinja', description: '45+ entertainment channels' },
  { id: 407, name: 'GOtv Jolli Bouquet', type: 'tv', provider: 'GOtv', price: 4850, plan_id: 'gotv_jolli', description: '65+ movies and sports' },
  { id: 408, name: 'GOtv Max Bouquet', type: 'tv', provider: 'GOtv', price: 7200, plan_id: 'gotv_max', description: 'La Liga, Serie A & WWE' },
  { id: 409, name: 'Startimes Basic Antenna', type: 'tv', provider: 'Startimes', price: 3000, plan_id: 'startimes_basic', description: 'Basic TV package' },
  { id: 410, name: 'Startimes Classic Dish', type: 'tv', provider: 'Startimes', price: 5000, plan_id: 'startimes_classic', description: 'Classic all channels' },

  // EDUCATION / EXAM PINS
  { id: 501, name: 'WAEC Result Checker PIN', type: 'education', provider: 'WAEC', price: 3450, description: 'Check WAEC May/June or Nov/Dec results online' },
  { id: 502, name: 'NECO Token (5 Result Checks)', type: 'education', provider: 'NECO', price: 1200, description: 'Official NECO token for checking 5 candidate results' },
  { id: 503, name: 'JAMB UTME e-PIN (With Mock)', type: 'education', provider: 'JAMB', price: 7700, description: 'Official JAMB UTME registration profile PIN' },
  { id: 504, name: 'NABTEB Result Checker PIN', type: 'education', provider: 'NABTEB', price: 1100, description: 'NABTEB May/June or Nov/Dec result verification' },

  // RECHARGE CARD PRINTING
  { id: 601, name: 'MTN Recharge Card Print', type: 'print_card', provider: 'MTN', price: 98, description: 'Wholesale batch printing for physical vouchers' },
  { id: 602, name: 'Airtel Recharge Card Print', type: 'print_card', provider: 'Airtel', price: 97.5, description: 'Wholesale batch printing' },
  { id: 603, name: 'Glo Recharge Card Print', type: 'print_card', provider: 'Glo', price: 96, description: 'Wholesale batch printing' },

  // BULK SMS
  { id: 701, name: 'Standard Corporate Route', type: 'bulk_sms', provider: 'BulkSMS', price: 3.5, description: 'Delivery to DND and Non-DND numbers with custom Sender ID' },

  // SOCIAL BOOST
  { id: 801, name: 'Instagram Followers (HQ Non-Drop)', type: 'social_boost', provider: 'Instagram', price: 1800, description: 'Per 1,000 real-looking followers' },
  { id: 802, name: 'TikTok High Retention Views', type: 'social_boost', provider: 'TikTok', price: 350, description: 'Per 10,000 algorithmic views' },
  { id: 803, name: 'YouTube Monetizable Watch Hours', type: 'social_boost', provider: 'YouTube', price: 4200, description: 'Per 1,000 organic hours' },

  // BUY LOGS
  { id: 901, name: 'Aged Twitter / X Account (2018-2021)', type: 'buy_logs', provider: 'Twitter', price: 4500, description: 'Includes original email + cookies + 2FA recovery backup' },
  { id: 902, name: 'Active Facebook Aged Account (5+ yrs)', type: 'buy_logs', provider: 'Facebook', price: 3800, description: '2FA enabled, marketplace access active' },
  { id: 903, name: 'Fresh USA Gmail + Recovery Mail', type: 'buy_logs', provider: 'Google', price: 650, description: 'PVA Verified with recovery backup codes' },
];

export const INITIAL_TRANSACTIONS: TransactionRecord[] = [
  {
    id: 'tx_1',
    reference: 'TXN-20260923-0891',
    type: 'data',
    title: 'MTN SME Data 2GB',
    recipient: '08034567890',
    details: 'Plan: mtn_sme_2gb · 30 Days',
    amount: 530,
    reseller_amount: 600,
    profit: 70,
    status: 'successful',
    wallet_balance_before: 69030,
    wallet_balance_after: 68500,
    created_at: '2026-09-23 06:15 AM',
    api_response: 'Data delivered successfully. MTN Balance valid for 30 days.',
  },
  {
    id: 'tx_2',
    reference: 'TXN-20260923-0874',
    type: 'electricity',
    title: 'Ikeja Electric Prepaid Token',
    recipient: '45028919283',
    details: 'Customer: ADEKUNLE JOHNSON · Ikeja GRA',
    amount: 5000,
    reseller_amount: 5100,
    profit: 100,
    status: 'successful',
    token: '4829-1940-2094-1184-9023',
    wallet_balance_before: 74030,
    wallet_balance_after: 69030,
    created_at: '2026-09-23 05:42 AM',
    api_response: 'Token: 4829-1940-2094-1184-9023 | Units: 58.4 kWh',
  },
  {
    id: 'tx_3',
    reference: 'TXN-20260922-0731',
    type: 'virtual_number',
    title: 'USA Number (WhatsApp Verification)',
    recipient: '+1 (202) 555-0194',
    details: 'Route: USA Server 1 · Provider: JejeLaye OTP',
    amount: 950,
    reseller_amount: 1200,
    profit: 250,
    status: 'completed',
    token: '729-104',
    wallet_balance_before: 74980,
    wallet_balance_after: 74030,
    created_at: '2026-09-22 10:14 PM',
    api_response: 'OTP Received: 729-104. Session marked completed.',
  },
  {
    id: 'tx_4',
    reference: 'TXN-20260922-0692',
    type: 'education',
    title: 'WAEC Result Checker PIN',
    recipient: 'Self / Client WhatsApp',
    details: 'Candidate WAEC 2026 Examination Checker',
    amount: 3450,
    reseller_amount: 3750,
    profit: 300,
    status: 'successful',
    token: 'WAC-89201948201',
    serial: 'SER-2026-WAEC-991',
    wallet_balance_before: 78430,
    wallet_balance_after: 74980,
    created_at: '2026-09-22 08:30 PM',
    api_response: 'PIN: WAC-89201948201 | Serial: SER-2026-WAEC-991',
  },
  {
    id: 'tx_5',
    reference: 'TXN-20260922-0450',
    type: 'esim',
    title: 'USA Travel eSIM 3GB (30 Days)',
    recipient: 'traveller.dan@example.com',
    details: 'QR Code & ICCID generated instantly',
    amount: 6800,
    reseller_amount: 7800,
    profit: 1000,
    status: 'completed',
    token: 'LPA:1$smdp.jejelaye.com$9A82D01938F2019',
    wallet_balance_before: 85230,
    wallet_balance_after: 78430,
    created_at: '2026-09-22 03:15 PM',
    api_response: 'QR Code payload generated. Sent to customer email.',
  },
];

export const INITIAL_ESIM_PACKAGES: EsimPackage[] = [
  { package_code: 'US-1GB-7D', title: 'United States 1GB (7 Days)', country: 'United States', flag: '🇺🇸', data_amount: '1GB', duration: '7 Days', price: 3200, category: 'country' },
  { package_code: 'US-3GB-30D', title: 'United States 3GB (30 Days)', country: 'United States', flag: '🇺🇸', data_amount: '3GB', duration: '30 Days', price: 6800, category: 'country' },
  { package_code: 'US-5GB-30D', title: 'United States 5GB (30 Days)', country: 'United States', flag: '🇺🇸', data_amount: '5GB', duration: '30 Days', price: 10500, category: 'country' },
  { package_code: 'UK-3GB-30D', title: 'United Kingdom 3GB (30 Days)', country: 'United Kingdom', flag: '🇬🇧', data_amount: '3GB', duration: '30 Days', price: 5900, category: 'country' },
  { package_code: 'UK-10GB-30D', title: 'United Kingdom 10GB (30 Days)', country: 'United Kingdom', flag: '🇬🇧', data_amount: '10GB', duration: '30 Days', price: 14200, category: 'country' },
  { package_code: 'EU-5GB-30D', title: 'Europe 33 Countries 5GB (30D)', country: 'European Union', flag: '🇪🇺', data_amount: '5GB', duration: '30 Days', price: 8900, category: 'regional' },
  { package_code: 'GLOBAL-3GB-15D', title: 'Global 135+ Countries 3GB', country: 'Global Roaming', flag: '🌐', data_amount: '3GB', duration: '15 Days', price: 12500, category: 'global' },
];

export const INITIAL_GIFT_CARDS: GiftCardRate[] = [
  { id: 'gc_1', name: 'Steam Wallet Card', slug: 'steam', currency: 'USD', physical_rate: 1350, ecode_rate: 1280, icon: '🎮' },
  { id: 'gc_2', name: 'Apple / iTunes Card', slug: 'apple', currency: 'USD', physical_rate: 1290, ecode_rate: 1220, icon: '🍎' },
  { id: 'gc_3', name: 'Amazon Gift Card', slug: 'amazon', currency: 'USD', physical_rate: 1260, ecode_rate: 1190, icon: '📦' },
  { id: 'gc_4', name: 'Google Play Store', slug: 'google-play', currency: 'USD', physical_rate: 1240, ecode_rate: 1180, icon: '▶️' },
  { id: 'gc_5', name: 'Razer Gold Pin', slug: 'razer-gold', currency: 'USD', physical_rate: 1380, ecode_rate: 1320, icon: '🟢' },
  { id: 'gc_6', name: 'Sephora / Nordstrom', slug: 'sephora', currency: 'USD', physical_rate: 1250, ecode_rate: 1180, icon: '💄' },
  { id: 'gc_7', name: 'Vanilla Visa / Amex', slug: 'vanilla-visa', currency: 'USD', physical_rate: 1180, ecode_rate: 1110, icon: '💳' },
];

export const INITIAL_GIFT_CARD_TRADES: GiftCardTrade[] = [
  {
    reference: 'GC-TRADE-8921',
    brand: 'Steam Wallet Card',
    currency: 'USD',
    card_country: 'US',
    card_type: 'physical',
    card_amount: 100,
    total_payout: 135000,
    reseller_payout: 138500,
    status: 'approved',
    created_at: '2026-09-22 04:30 PM',
  },
  {
    reference: 'GC-TRADE-8842',
    brand: 'Amazon Gift Card',
    currency: 'USD',
    card_country: 'US',
    card_type: 'ecode',
    card_amount: 50,
    total_payout: 59500,
    ecode: 'AQ29-1928-KK29-9182',
    status: 'approved',
    created_at: '2026-09-21 07:12 PM',
  },
];

export const INITIAL_VIRTUAL_SESSIONS: VirtualNumberSession[] = [
  {
    reference: 'VNS-20260923-01',
    category: 'usa',
    server_key: 'usa_server_1',
    service_name: 'WhatsApp',
    service_code: 'whatsapp',
    phone_number: '+1 (202) 555-0142',
    status: 'completed',
    otp: '918-204',
    cost: 950,
    reseller_cost: 1200,
    created_at: '2026-09-23 06:05 AM',
    expires_at: Date.now() + 10 * 60 * 1000,
  },
  {
    reference: 'VNS-20260923-02',
    category: 'international',
    server_key: 'international_server_1',
    service_name: 'Telegram',
    service_code: 'telegram',
    phone_number: '+44 7700 900381',
    status: 'waiting_for_otp',
    cost: 1100,
    reseller_cost: 1350,
    created_at: '2026-09-23 06:40 AM',
    expires_at: Date.now() + 15 * 60 * 1000,
  },
];

export const NIGERIAN_BANKS = [
  { code: '044', name: 'Access Bank' },
  { code: '023', name: 'Citibank Nigeria' },
  { code: '050', name: 'Ecobank Nigeria' },
  { code: '070', name: 'Fidelity Bank' },
  { code: '011', name: 'First Bank of Nigeria' },
  { code: '214', name: 'First City Monument Bank (FCMB)' },
  { code: '058', name: 'Guaranty Trust Bank (GTBank)' },
  { code: '030', name: 'Heritage Bank' },
  { code: '301', name: 'Jaiz Bank' },
  { code: '082', name: 'Keystone Bank' },
  { code: '100004', name: 'Opay Digital Services' },
  { code: '999992', name: 'OPay / Paycom' },
  { code: '100033', name: 'PalmPay Limited' },
  { code: '076', name: 'Polaris Bank' },
  { code: '101', name: 'Providus Bank' },
  { code: '221', name: 'Stanbic IBTC Bank' },
  { code: '068', name: 'Standard Chartered Bank' },
  { code: '232', name: 'Sterling Bank' },
  { code: '100', name: 'Suntrust Bank' },
  { code: '102', name: 'Titan Trust Bank' },
  { code: '032', name: 'Union Bank of Nigeria' },
  { code: '033', name: 'United Bank for Africa (UBA)' },
  { code: '215', name: 'Unity Bank' },
  { code: '035', name: 'Wema Bank' },
  { code: '057', name: 'Zenith Bank' },
  { code: '090551', name: 'FairMoney Microfinance Bank' },
  { code: '090405', name: 'Moniepoint Microfinance Bank' },
  { code: '090267', name: 'Kuda Microfinance Bank' },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-9021',
    subject: 'Data Delivery Confirmation Inquiry',
    message: 'Hello, the 2GB MTN SME data sent to 08034567890 reflected within 3 seconds. Just verifying confirmation reference.',
    transaction_reference: 'TXN-20260923-0891',
    status: 'answered',
    created_at: '2026-09-23 06:20 AM',
    replies: [
      {
        sender: 'support',
        message: 'Hello Emmanuel, yes! The transaction is fully confirmed and settled on the telco network. Thank you for using JejeLaye API.',
        time: '2026-09-23 06:22 AM',
      },
    ],
  },
];

export const INITIAL_PAYOUT_SETTINGS = {
  is_pin_set: true,
  daily_limit: 500000,
  daily_withdrawn: 45000,
  preferred_bank: {
    bank_name: 'Guaranty Trust Bank (GTBank)',
    bank_code: '058',
    account_number: '0124892184',
    account_name: 'EMMANUEL RESELLER TECH',
    is_verified: true,
  },
  settlement_schedule: 'instant' as const,
  require_2fa_for_payout: true,
};

export const INITIAL_PAYOUTS = [
  {
    id: 'PO-88219',
    reference: 'PAYOUT-20260923-001',
    source: 'margins' as const,
    amount: 25000,
    fee: 25,
    net_payout: 24975,
    bank_name: 'Guaranty Trust Bank (GTBank)',
    bank_code: '058',
    account_number: '0124892184',
    account_name: 'EMMANUEL RESELLER TECH',
    nip_session_id: '100004240923081923891048192019',
    status: 'settled' as const,
    settlement_mode: 'instant' as const,
    created_at: '2026-09-23 07:15 AM',
    settled_at: '2026-09-23 07:15 AM',
  },
  {
    id: 'PO-88218',
    reference: 'PAYOUT-20260922-094',
    source: 'gift_card' as const,
    amount: 50000,
    fee: 25,
    net_payout: 49975,
    bank_name: 'Moniepoint Microfinance Bank',
    bank_code: '090405',
    account_number: '6281928410',
    account_name: 'EMMANUEL TECH ENTERPRISES',
    nip_session_id: '100004240922091240182910482910',
    status: 'settled' as const,
    settlement_mode: 'instant' as const,
    created_at: '2026-09-22 04:30 PM',
    settled_at: '2026-09-22 04:31 PM',
  },
  {
    id: 'PO-88217',
    reference: 'PAYOUT-20260921-042',
    source: 'main_balance' as const,
    amount: 15000,
    fee: 25,
    net_payout: 14975,
    bank_name: 'Zenith Bank',
    bank_code: '057',
    account_number: '2109482910',
    account_name: 'EMMANUEL OWIGHOYOTA',
    nip_session_id: '100004240921074819201928471928',
    status: 'settled' as const,
    settlement_mode: 'daily_batch' as const,
    created_at: '2026-09-21 06:00 PM',
    settled_at: '2026-09-21 06:02 PM',
  },
];

export const INITIAL_PAYMENT_TRANSACTIONS = [
  {
    id: 'PAY-901',
    reference: 'JEJE_PAY_1727078219_A812',
    customer_name: 'Chidi Okonkwo',
    customer_email: 'chidi.o@gmail.com',
    customer_phone: '08023456789',
    service_title: 'MTN SME Data 5GB',
    service_type: 'data' as const,
    service_recipient: '08023456789',
    subtotal: 1450,
    reseller_margin: 125,
    gateway_fee: 22,
    total_amount: 1472,
    channel: 'card' as const,
    status: 'successful' as const,
    payment_details: {
      card_last4: '4112',
      card_brand: 'Mastercard',
      paid_at: '2026-09-23 07:10 AM',
      authorization_code: 'AUTH_8910283',
    },
    fulfillment_status: 'fulfilled' as const,
    fulfillment_token: 'MTN-SME-9821-OK',
    created_at: '2026-09-23 07:08 AM',
  },
  {
    id: 'PAY-902',
    reference: 'JEJE_PAY_1727076100_K921',
    customer_name: 'Amina Bello',
    customer_email: 'amina.b@yahoo.com',
    customer_phone: '08139281720',
    service_title: 'USA WhatsApp Virtual Number',
    service_type: 'virtual_number' as const,
    service_recipient: '+1 (347) 891-2091',
    subtotal: 2200,
    reseller_margin: 400,
    gateway_fee: 33,
    total_amount: 2233,
    channel: 'bank_transfer' as const,
    status: 'successful' as const,
    payment_details: {
      bank_name: 'Wema Bank',
      virtual_account: '9820194812',
      paid_at: '2026-09-23 06:45 AM',
    },
    fulfillment_status: 'fulfilled' as const,
    fulfillment_token: 'OTP: 839-201',
    created_at: '2026-09-23 06:40 AM',
  },
  {
    id: 'PAY-903',
    reference: 'JEJE_PAY_1727065000_X419',
    customer_name: 'David Adeleke',
    customer_email: 'david.a@gmail.com',
    customer_phone: '07038192841',
    service_title: 'Ikeja Electric (IKEDC) Prepaid',
    service_type: 'electricity' as const,
    service_recipient: '010192847192',
    subtotal: 5100,
    reseller_margin: 100,
    gateway_fee: 76,
    total_amount: 5176,
    channel: 'card' as const,
    status: 'successful' as const,
    payment_details: {
      card_last4: '1948',
      card_brand: 'Visa',
      paid_at: '2026-09-23 05:30 AM',
    },
    fulfillment_status: 'fulfilled' as const,
    fulfillment_token: 'TOKEN: 4819-2094-8172-0491-8271',
    created_at: '2026-09-23 05:25 AM',
  },
];

